In [11]:
import numpy as np
import pandas as pd

In [12]:
# Задаём максимально количкство строк для вывода
# pd.options.display.max_rows = 100

In [13]:
df = pd.read_csv(r"report.csv",
                  sep=',', decimal='.')
names = df.columns

In [14]:
df

MIP      STDIP      EKIP        SIP         MC       STDC  \
0    67.664062  32.561787  2.028000   8.098344   8.266722  34.838902   
1    65.226562  35.696904  2.291891  10.118479  15.515050  48.872426   
2    69.210938  45.266166  2.024291   4.485091   2.546823  18.201225   
3    65.796875  46.205106  2.289091   6.235283  20.372074  51.022074   
4    69.210938  36.152380  2.602622  11.032994  11.813545  41.382661   
..         ...        ...       ...        ...        ...        ...   
197  95.093750  46.560854  0.586803   0.409974   2.747492  20.590768   
198  94.812500  45.756275  0.637962   0.920456   6.995819  33.609639   
199  65.203125  33.163977  2.861041  12.804505  44.520903  75.761212   
200  94.671875  45.477348  0.435846   0.676577   0.899666  12.548766   
201  94.773438  37.718782  0.538717   1.536012   1.431438  11.224353   

           EKC          SC  TARGET  
0     4.793382   24.032048       1  
1     3.185367    9.164036       1  
2     9.997593  109.122306       1  
3     2.941692    8.457182       1  
4     3.902658   15.151920       1  
..         ...         ...     ...  
197   7.940477   65.508377       0  
198   4.950313   24.080654       0  
199   1.369637    0.316789       1  
200  15.473803  257.052253       0  
201  13.800653  252.822918       0  

[202 rows x 9 columns]

In [15]:
# Определите выборочное среднее для столбца MIP
df['MIP'].mean()


81.34007580445545

In [16]:
# Выполните линейную нормировку всех значений предикторов полученной выборки
from sklearn import preprocessing
# Нормировака 1. Для отдельного столбца:
# x_array = np.array(df['MIP'])
# normalized_arr = preprocessing.normalize([x_array])
# Определите выборочное среднее для столбца MIP после нормировки
# np.mean(normalized_arr)

In [17]:
# Нормировка 2. Для всей выборки:
# d = preprocessing.normalize(df)
# scaled_df = pd.DataFrame(d, columns=names)
# Определите выборочное среднее для столбца MIP после нормировки
# scaled_df['MIP'].mean()


In [18]:
# Нормировка 3. Для всей выборки:
scaler = preprocessing.MinMaxScaler()
d = scaler.fit_transform(df)
scaled_df = pd.DataFrame(d, columns=names)
# Определите выборочное среднее для столбца MIP после нормировки
scaled_df['MIP'].mean()

0.5382802438506071

In [19]:
# Обучение модели логистической регрессии
# Подключение модели логистической регрессии из библиотеки sklearn
from sklearn.linear_model import LogisticRegression


In [20]:
# Отбор данных для предикторов, удаление последнего столбца, индекс не включается в данные автоматически.
X = pd.DataFrame(scaled_df.drop(['TARGET'], axis=1))
# Отбор столбца для отклика
y = pd.DataFrame(scaled_df['TARGET']).values.ravel()

In [21]:
# Подключение библиотеки и задание параметров модели: n_neighbors — число соседей; p — используемое расстояние. Манхэттенское расстояние — p=1, евклидово расстояние — p=2.
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5, p=2)
neigh.fit(X, y)

KNeighborsClassifier()

In [22]:
# Новый объект, который необходимо классифицировать
NewObject = [0.254, 0.19, 0.939, 0.624, 0.935, 0.875, 0.151, 0.312]

In [23]:
# Назначенный класс:
neigh.predict([NewObject])

array([1.])

In [24]:
# Вероятности отнесения к классам 0 и 1 соответственно:
neigh.predict_proba([NewObject])

array([[0., 1.]])

In [25]:
# Вывод расстояний до k соседей в порядке удаления (первый массив — расстояния, второй — идентификаторы объектов). Обращаем внимание, что метод возвращает индексы ближайших соседей с нуля, что не соответствует индексации в таблице.
neigh.kneighbors([NewObject])

(array([[0.60717192, 0.63562366, 0.7012051 , 0.72964615, 0.73001303]]),
 array([[127, 119, 102,  36,  44]], dtype=int64))